### ISSUE TITLE
Where can I find the solutions for exercises for compGenomRData

### ISSUE THREAD

**Issue by tsekara** [compgenomr/compGenomRData#4]
Dear Sir,

Thank you very much for making Computational genomics R. I liked it very much and going through all the chapters and exercises. I want to know where can I find the solutions for the exercises mentioned in the book. Kindly guide me. thanks in advance

**Comment by HerderB** [comment]
I'd also like to know where I can find the solutions to see if I used the best approach possible or help when I'm stuck.

**Comment by al2na** [comment]
we will put this up. I'm sidetracked with homeschooling, taking care of
kids etc.

**Comment by al2na** [comment]
we started putting up the exercises
