### ISSUE TITLE
Failed to install compGenomeRData.

### ISSUE THREAD

**Issue by arriyaz** [compgenomr/compGenomRData#6]
When I tried to install compGenomeRData by using code:
`devtools::install_github("compgenomr/compGenomRData")`

I am getting this error:

`Error: Failed to install 'compGenomRData' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)
In addition: Warning messages:
1: In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Users\riYaz\AppData\Local\Temp\Rtmpkzp96L\fileb6c59027e80.tar.gz" -C "C:/Users/riYaz/AppData/Local/Temp/Rtmpkzp96L/remotesb6c41c63d88"’ returned error code 1
2: In system(cmd, intern = TRUE) :
  running command 'tar.exe -tf "C:\Users\riYaz\AppData\Local\Temp\Rtmpkzp96L\fileb6c59027e80.tar.gz"' had status 1`

**Comment by al2na** [comment]
I can't reproduce this, it works for me
![image](https://user-images.githubusercontent.com/638225/106146434-f20e7100-6176-11eb-8781-fca9c6614262.png)

re-open when you have a reproducible or at least more detailed case.

**Comment by al2na** [comment]
try installing rtools and re-try the command, that does the trick for some windows users
