### ISSUE TITLE
can't install compGenomRData, link to exercise solutions invalid

### ISSUE THREAD

**Issue by gkuhlenbaum** [compgenomr/compGenomRData#7]
Dear Dr. Alkalin,

I have two problems with your nice book:
1. can't install package with data:
> devtools::install_github("compgenomr/compGenomRData")
Downloading GitHub repo compgenomr/compGenomRData@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/compgenomr/compGenomRData/tarball/HEAD' failed 

Also tried githubinstall::githubinstall("compgenomr/compGenomRData") which did not work

2. Link: "https://github.com/compgenomr/exercises" leads to 404 error - no page under this address.

I would be very grateful if you could tell me how to solve these problems.

Yours sincerely

Gregor

**Comment by al2na** [comment]
I can't reproduce 1. , it works for me
![image](https://user-images.githubusercontent.com/638225/106146434-f20e7100-6176-11eb-8781-fca9c6614262.png)

re-open when you have a reproducible or at least more detailed case. The exercises are on the way

**Comment by al2na** [comment]
try installing rtools and re-try the command for installing book data, that does the trick for some windows users
