### ISSUE TITLE
Missing files rn4.refseq.bed and rn4.refseq2name.txt

### ISSUE THREAD

**Issue by HerderB** [compgenomr/compGenomRData#8]
Hello,

For exercise 12 in section 2.10.3, I need 2 files, rn4.refseq.bed and rn4.refseq2name.txt. However, these are not present in extdata.

**Comment by al2na** [comment]
they should be there now, you might have to re-install by setting force=TRUE

**Comment by HerderB** [comment]
Thank you, the data is now present after reinstall.
